AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  CodeS3Location:
    Type: String
    Default: s3://vape-artifacts/dsp-lambda-engine/dsp-aws-lambda-dist.zip
    Description: the location of code zip file in s3
  DeployPreference:
    Type: String
    Default: AllAtOnce
    AllowedValues:
      - # Don't allow other type
      - AllAtOnce
      - Canary10Percent5Minutes
Resources:
  rootMeanSquare:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rootMeanSquare
      AutoPublishAlias: dev
      Role: arn:aws:iam::742872122332:role/lambda_invoke_function_assume_apigw_role.
      CodeUri:
        Ref: CodeS3Location
      Handler: src/algorithms/rms/RMS.lambda_entry
      Runtime: python3.7
      DeploymentPreference:
        Type:
          Ref: DeployPreference
  kurtosis:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kurtosis
      AutoPublishAlias: dev
      Role: arn:aws:iam::742872122332:role/lambda_invoke_function_assume_apigw_role.
      CodeUri:
        Ref: CodeS3Location
      Handler: src/algorithms/kurtosis/Kurtosis.lambda_entry
      Runtime: python3.7
      DeploymentPreference:
        Type:
          Ref: DeployPreference
  fft:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fft
      AutoPublishAlias: dev
      Role: arn:aws:iam::742872122332:role/lambda_invoke_function_assume_apigw_role.
      CodeUri:
        Ref: CodeS3Location
      Handler: src/algorithms/fft/FFT.lambda_entry
      Runtime: python3.7
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:2
      DeploymentPreference:
        Type:
          Ref: DeployPreference